config/routes.rb
Task5::Application.routes.draw do
  resources :comments
  
  root :to => "articles#index" 
  resources :articles

  get 'export', to: 'articles#export', as: :article_export

  resources :articles do
    collection { post :import }
  end

  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  require 'csv'
  #attr_accessible :title, :content, :status
  #name relation must plural
  has_many :comments, dependent: :destroy
  paginates_per 2

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv.add_row column_names
      all.each do |article|
        values = article.attributes.values
        csv.add_row values
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      article_hash = row.to_hash
      article = Article.where(id: article_hash["id"])
      if article.count == 1
        article.first.update_attributes(article_hash)
      else
        Article.create!(article_hash)
      end
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #name relation must singular
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order('id ASC').page(params[:page]).per(5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article=Article.find(params[:id])
    @comments=@article.comments
    @comment=@article.comments.build
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find_by_id(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
     @article = Article.find_by_id(params[:id]).comments.first.update(content: "edited comment")
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  #export
  def export
    @article = Article.order(:id)
    respond_to do |format|
      format.html { redirect_to root_url }
      format.csv { send_data @article.to_csv, filename: "Export-#{Date.today}.csv" }
      format.xls #{ send_data @article.to_csv(col_sep: "\t"), filename: "Export-#{Date.today}.xls" }
    end
  end

  #import
  def import
    Article.import(params[:file])
    redirect_to root_url, notice: "Articles imported"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @article = Article.find(params[:article_id])
    @comment =@article.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:article_id, :content, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, cols: 20, rows: 10 %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.radio_button :status, "Active", :checked => true %>
    <%= label :article_status, 'Active' %>
    <%= f.radio_button :status, "Off" %>
    <%= label :article_status, 'Off' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Articles">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Title</Data></Cell>
        <Cell><Data ss:Type="String">Content</Data></Cell>
        <Cell><Data ss:Type="String">Status</Data></Cell>
      </Row>
      <% @article.each do |article| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= article.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.title %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.content %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.status %></Data></Cell>        
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<p><%= link_to 'New Article', new_article_path %></p>
<p><%= link_to "Export Data CSV", article_export_path(format: "csv") %></p>
<p><%= link_to "Export Data XLS", article_export_path(format: "xls") %></p>

<%= form_tag import_articles_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<% @articles.each do |article| %>
  <h3><%= article.id %>.<%= article.title %></h3>
 <p>
  <%= article.content.truncate(20) %>
  <%= link_to 'read more', article_path(article.id) %>
 </p>
  <h4>status : <%= article.status %></h4>
 <p>
  <span><%= link_to 'edit', edit_article_path(article.id) %><span>
  <span> | <span>
  <span><%= link_to 'delete', article_path(article.id), method: "DELETE", data: {confirm: 'Delete this data ? '} %><span>
 </p>
<hr/>
<% end -%>
<%= paginate @articles %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @article.status %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

<br><br>
Comments for article:<br>
<% @comments.each do |comment| -%>
 <p>
   <%= comment.content %> 
 </p>
<% end -%>     

<%= form_for [@article, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %>
        prohibited this comment from being saved: </h2>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>   
    </div>
  <% end %>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :content %>
    <%= flash[:notice] %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
    <%= flash[:notice] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br>
    <%= f.number_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>Content</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.article_id %></td>
        <td><%= comment.content %></td>
        <td><%= comment.status %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @comment.status %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task5</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>